# Definición de los servicios (contenedores) que compondrán tu aplicación
services:
  # Nombre del servicio de tu aplicación Nuxt
  dos-venados-site:
    image: node:20.15.0
    working_dir: /app
    ports:
      - "3031:3000"
    environment:
      - HOST=0.0.0.0
    volumes:
      - .:/app

    # --- ESTA ES LA LÍNEA A CORREGIR ---
    # Usa esta sintaxis para que el shell del contenedor ejecute los comandos
    command: sh -c "npm install && npm run dev"

networks:
  dynamic_home_network:
    external: true