# Definici칩n de los servicios (contenedores) que compondr치n tu aplicaci칩n
services:
  # Nombre del servicio de tu aplicaci칩n Nuxt
  dos-venados-site:
    build:
      context: .
    container_name: dos-venados-site
    restart: always
    ports:
      - "3000:80"
    networks:
      - dmit_network
  

networks:
  dynamic_home_network:
    external: true